version: '3.2'

services:
  teleglogger:
    image: t0mk/teleglogger
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - TG
      - TG_CHAT
      - TG_TOKEN
      - MATCHRE
      - DEBUG  
